### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by KarthikRaja1388** [nuzelac/matomoanalyticsjs#1]
I would like to know whether this module is still maintained.

**Comment by nuzelac** [comment]
Why?

**Comment by KarthikRaja1388** [comment]
We have received an email saying that the developer of this module confirmed that this module is not maintained anymore and requested us to remove the module from the website. It sounded bit dodgy, so just want to check with you.

**Comment by nuzelac** [comment]
Eh, I'm not the original developer unfortunately :) I forked it from a website just to have user tracking removed for GDPR.

The upstream module is still up at https://dh42.com/free-prestashop-modules/prestashop-piwik-statistics/ so I would check with them.

**Comment by KarthikRaja1388** [comment]
Got in touch with dh42 support and they confirmed that the module is maintained for PrestaShop version 1.6.
